### PR TITLE
Python package structure

### PR DESCRIPTION
**Pull request by nschloe**
Add a proper Python package structure so this can by published easily on PyPi.

With the changes, you can install the package locally with
```
pip install .
```
For uploading to PyPi, I've added a `Makefile`. You can `make publish` to create a release on GitHub and upload to PyPi.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
If I understand well, this leaves pip the only way to install the package, does it? My primary OS is Arch Linux. After [Arch Wiki](https://wiki.archlinux.org/index.php/Python_package_guidelines#pip):

> Warning: Use of pip and/or wheel packages is discouraged in favor of setuptools source packages, and should only be used when the latter is not a viable option (for example, packages which only come with wheel sources, and therefore cannot be installed using setuptools).

**Comment by nschloe** [comment]
> If I understand well, this leaves pip the only way to install the package, does it?

No, it work with setuptools as well; pip is just a handy installer. You can run
```
python3 -m pep517.build --source --binary .
```
to check.

**Comment by nschloe** [comment]
If you want the old `setup.py` back so you can go
```
python3 setup.py build
```
etc. I could add that, too. It's not necessary though with recent versions of setuptools, see the above command.

**Comment by nwg-piotr** [comment]
I just wonder what the new PKGBUILD should look like. The [old one](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=autotiling) is simplified and against python packaging rules.

**Comment by nschloe** [comment]
What do other PKGBUILD against small pypi packages look like? Perhaps check [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-meshio)?

**Comment by nwg-piotr** [comment]
i3ipc can be found in PyPi, still it uses `python setup.py install --root="${pkgdir}" --optimize=1`.

**Comment by nschloe** [comment]
Let me add a setup.py, just a minute.

**Comment by nwg-piotr** [comment]
Excellent.

**Comment by nschloe** [comment]
Done.

**Comment by nwg-piotr** [comment]
Could you also bump the version to 1.1?

**Comment by nschloe** [comment]
Done.

**Comment by nwg-piotr** [comment]
Alright, I'll merge and publish a pre-release to check it out.

**Comment by nschloe** [comment]
Cool. Just ping me if we need anything else.

**Comment by nwg-piotr** [comment]
Erm..., doesn't seem to work for me:

> $ sudo pip install autotiling
> ERROR: Could not find a version that satisfies the requirement autotiling (from versions: none)
> ERROR: No matching distribution found for autotiling

**Comment by nschloe** [comment]
```
sudo pip install autotiling
```
Okay, so since recently pip supports user installs, so it's discouraged to use it with `sudo`. (Finally!)
This line won't work for you because it's not on pypi yet:

https://pypi.org/project/autotiling/

You can also use pip to install local package like
```
pip install /path/to/package/
```
e.g.,
```
pip install .
```
(This as some advantages over using a purely `setup.py`-based approach, an important one being that you can uninstall packages with `pip uninstall <packagename>`.)

**Comment by nschloe** [comment]
> and system-wide I always use Arch packages.

I used to do the same thing, just with Debian till I gave pypi packages a spin. I found they are _so_ easy to update and most of all to install that I hardly use anything else anymore. I'm sure you'll find it it useful as well.

**Comment by nwg-piotr** [comment]
Alright, no hurry. The PKGBUILD works well, although complains about the `wheel` package missing. It's not necessary, right?

**Comment by nschloe** [comment]
I don't know Arch.

**Comment by nwg-piotr** [comment]
The message must come from here:

```
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
```

**Comment by nschloe** [comment]
Ah. Yeah, no idea why arch won't install it. `wheel` is a pretty standard package, it builds the "wheel", sort of a compiled binary. Usually when people go `pip install <package_name>`, it searches pypi, finds the wheel and installs it right away. If pip only finds a `tar.gz`, it has to build first. (That's necessary for some packages that depend on system libraries.)

**Comment by nwg-piotr** [comment]
I could add wheel to `makedepends`, but it seems to have no job to do.

**Comment by nschloe** [comment]
If it works, it works. I'd also leave it out.

**Comment by nwg-piotr** [comment]
Very well. Thank you for your contribution.

BTW: I haven't ever expected the script 50 SLOC long to have that many contributors! :D

**Comment by nschloe** [comment]
You still need to upload the package to pypi: https://pypi.org/project/autotiling/

**Comment by nwg-piotr** [comment]
Indeed.

I wonder why the hell the `make publish` command shows me error messages concerning another script.

```
$ make publish
curl -H "Authorization: token `cat /home/piotr/.github-access-token`" -d '{"tag_name": "v1.1"}' https://api.github.com/repos/nwg-piotr/autotiling/releases
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Release",
      "code": "already_exists",
      "field": "tag_name"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/repos/releases/#create-a-release"
}
# Make sure we're on the master branch
rm -f dist/*
# https://stackoverflow.com/a/58756491/353337
python3 -m pep517.build --source --binary .
ERROR: obhud 0.2.3 requires alsa-utils, which is not installed.
ERROR: obhud 0.2.3 requires ffmpeg, which is not installed.
ERROR: obhud 0.2.3 requires libxrandr, which is not installed.
ERROR: obhud 0.2.3 requires python, which is not installed.
ERROR: obhud 0.2.3 requires python-lxml, which is not installed.
ERROR: obhud 0.2.3 requires python-pillow, which is not installed.
ERROR: obhud 0.2.3 requires python-pmw, which is not installed.
ERROR: obhud 0.2.3 requires xf86-input-synaptics, which is not installed.
ERROR: obhud 0.2.3 requires xorg-xbacklight, which is not installed.
ERROR: obhud 0.2.3 requires xorg-xrandr, which is not installed.
ERROR: obhud 0.2.3 requires alsa-utils, which is not installed.
ERROR: obhud 0.2.3 requires ffmpeg, which is not installed.
ERROR: obhud 0.2.3 requires libxrandr, which is not installed.
ERROR: obhud 0.2.3 requires python, which is not installed.
ERROR: obhud 0.2.3 requires python-lxml, which is not installed.
ERROR: obhud 0.2.3 requires python-pillow, which is not installed.
ERROR: obhud 0.2.3 requires python-pmw, which is not installed.
ERROR: obhud 0.2.3 requires xf86-input-synaptics, which is not installed.
ERROR: obhud 0.2.3 requires xorg-xbacklight, which is not installed.
ERROR: obhud 0.2.3 requires xorg-xrandr, which is not installed.
running sdist
running egg_info
writing autotiling.egg-info/PKG-INFO
writing dependency_links to autotiling.egg-info/dependency_links.txt
writing entry points to autotiling.egg-info/entry_points.txt
writing requirements to autotiling.egg-info/requires.txt
writing top-level names to autotiling.egg-info/top_level.txt
reading manifest file 'autotiling.egg-info/SOURCES.txt'
writing manifest file 'autotiling.egg-info/SOURCES.txt'
running check
creating autotiling-1.1
creating autotiling-1.1/autotiling
creating autotiling-1.1/autotiling.egg-info
copying files to autotiling-1.1...
copying LICENSE -> autotiling-1.1
copying README.md -> autotiling-1.1
copying pyproject.toml -> autotiling-1.1
copying setup.cfg -> autotiling-1.1
copying setup.py -> autotiling-1.1
copying autotiling/__about__.py -> autotiling-1.1/autotiling
copying autotiling/__init__.py -> autotiling-1.1/autotiling
copying autotiling/main.py -> autotiling-1.1/autotiling
copying autotiling.egg-info/PKG-INFO -> autotiling-1.1/autotiling.egg-info
copying autotiling.egg-info/SOURCES.txt -> autotiling-1.1/autotiling.egg-info
copying autotiling.egg-info/dependency_links.txt -> autotiling-1.1/autotiling.egg-info
copying autotiling.egg-info/entry_points.txt -> autotiling-1.1/autotiling.egg-info
copying autotiling.egg-info/requires.txt -> autotiling-1.1/autotiling.egg-info
copying autotiling.egg-info/top_level.txt -> autotiling-1.1/autotiling.egg-info
Writing autotiling-1.1/setup.cfg
Creating tar archive
removing 'autotiling-1.1' (and everything under it)
ERROR: obhud 0.2.3 requires alsa-utils, which is not installed.
ERROR: obhud 0.2.3 requires ffmpeg, which is not installed.
ERROR: obhud 0.2.3 requires libxrandr, which is not installed.
ERROR: obhud 0.2.3 requires python, which is not installed.
ERROR: obhud 0.2.3 requires python-lxml, which is not installed.
ERROR: obhud 0.2.3 requires python-pillow, which is not installed.
ERROR: obhud 0.2.3 requires python-pmw, which is not installed.
ERROR: obhud 0.2.3 requires xf86-input-synaptics, which is not installed.
ERROR: obhud 0.2.3 requires xorg-xbacklight, which is not installed.
ERROR: obhud 0.2.3 requires xorg-xrandr, which is not installed.
ERROR: obhud 0.2.3 requires alsa-utils, which is not installed.
ERROR: obhud 0.2.3 requires ffmpeg, which is not installed.
ERROR: obhud 0.2.3 requires libxrandr, which is not installed.
ERROR: obhud 0.2.3 requires python, which is not installed.
ERROR: obhud 0.2.3 requires python-lxml, which is not installed.
ERROR: obhud 0.2.3 requires python-pillow, which is not installed.
ERROR: obhud 0.2.3 requires python-pmw, which is not installed.
ERROR: obhud 0.2.3 requires xf86-input-synaptics, which is not installed.
ERROR: obhud 0.2.3 requires xorg-xbacklight, which is not installed.
ERROR: obhud 0.2.3 requires xorg-xrandr, which is not installed.
running bdist_wheel
running build
running build_py
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/autotiling
copying build/lib/autotiling/__about__.py -> build/bdist.linux-x86_64/wheel/autotiling
copying build/lib/autotiling/main.py -> build/bdist.linux-x86_64/wheel/autotiling
copying build/lib/autotiling/__init__.py -> build/bdist.linux-x86_64/wheel/autotiling
running install_egg_info
running egg_info
writing autotiling.egg-info/PKG-INFO
writing dependency_links to autotiling.egg-info/dependency_links.txt
writing entry points to autotiling.egg-info/entry_points.txt
writing requirements to autotiling.egg-info/requires.txt
writing top-level names to autotiling.egg-info/top_level.txt
reading manifest file 'autotiling.egg-info/SOURCES.txt'
writing manifest file 'autotiling.egg-info/SOURCES.txt'
Copying autotiling.egg-info to build/bdist.linux-x86_64/wheel/autotiling-1.1-py3.8.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/autotiling-1.1.dist-info/WHEEL
creating '/tmp/tmpksq0ae5q/tmp6dkrk_0a/autotiling-1.1-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'autotiling/__about__.py'
adding 'autotiling/__init__.py'
adding 'autotiling/main.py'
adding 'autotiling-1.1.dist-info/LICENSE'
adding 'autotiling-1.1.dist-info/METADATA'
adding 'autotiling-1.1.dist-info/WHEEL'
adding 'autotiling-1.1.dist-info/entry_points.txt'
adding 'autotiling-1.1.dist-info/top_level.txt'
adding 'autotiling-1.1.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
twine upload dist/*
Enter your username: nwg-piotr
/usr/lib/python3.8/site-packages/twine/utils.py:219: UserWarning: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
  warnings.warn(str(exc))
Enter your password:
Uploading distributions to https://upload.pypi.org/legacy/
Uploading autotiling-1.1-py3-none-any.whl
100%|██████████████████████████████████████████████████████████████| 22.0k/22.0k [00:02<00:00, 8.37kB/s]
Uploading autotiling-1.1.tar.gz
100%|██████████████████████████████████████████████████████████████| 21.3k/21.3k [00:01<00:00, 16.2kB/s]

View at:
https://pypi.org/project/autotiling/1.1/
```

**Comment by nschloe** [comment]
> ERROR: obhud 0.2.3 requires alsa-utils, which is not installed.

I get that sometimes as well (with other packages). It's a Python (setuptools?) weirdness: If your Python installation is incomplete, it will notify you everytime it notices.

**Comment by nwg-piotr** [comment]
LOL, thanks for explanation. :)

**Pull request merged**
