### PR TITLE
add --version

### PR DESCRIPTION
**Pull request by nschloe**

### CODE REVIEW

**Comment by nwg-piotr** [comment]
This needs a version bump to 1.2 and a new release, to avoid breaking packages.

**Comment by nschloe** [comment]
This just adds something, right?

**Comment by nwg-piotr** [comment]
The checksum's going to change.

**Comment by nschloe** [comment]
I mean, sure I can bump the version, but I don't get it. What checksum?

**Comment by nschloe** [comment]
Ah, were you thinking of releasing this same thing under 1.1? Of course not. I can bump to 1.2 so you can make a release immediately. I'd just have waited for a few more changes to accumulate I guess.

**Comment by nwg-piotr** [comment]
I never expect further changes, but they always come :) Sure, no hurry.

**Pull request merged**
