### PR TITLE
adds --workspace cli argument to restrict autotiling to certain workspaces

### PR DESCRIPTION
**Pull request by riscie**
Hi there!

Thank you so much for this nice little tool. I needed a way to restrict the autotiling to certain workspaces.
I hope it's in your spirit ;)

Usage:
`autotiling --workspaces 8 9`

Debug Output:
`autotiling is only active on workspaces: 8,9`

I am not doing too much python these days, so I hope this PR is kinda fine ;)

cheers, riscie

### CODE REVIEW

**Comment by riscie** [comment]
Sorry there was a bug in my initial commit. I hope it works out now.

**Comment by nwg-piotr** [comment]
Good idea, thanks. I'll take a closer look later today. At the moment I'm thinking in golang. :smiley:

**Comment by riscie** [comment]
golang, arch, i3/sway... :heart:   you are doing all the good things my friend :wink:

**Comment by nwg-piotr** [comment]
Haha, thank you! I'm just a hobbyist programmer, and a greenhorn in Go. [This](https://github.com/nwg-piotr/nwgocc) is my first serious code.

**Review by nwg-piotr — CHANGES_REQUESTED** [review]
Good and useful idea. I suggest 2 changes:

1. Workspace name does not necessarily must be like "1" or "8". E.g. I rename workspaces dynamically, after the name of the last focused window, and add and icon and an arrow indicating the split orientation, with [this script](https://github.com/nwg-piotr/swayinfo/blob/master/wsdnames.py).

image

For your modification to behave properly in such cases, instead of:

```python
if con and not workspaces or (con.workspace().name in workspaces):
``` 

we could use:

```python
if con and not workspaces or (str(con.workspace().num) in workspaces):
```

2. On workspaces w/ autotiling turned off, the debug message may be misleading, as it's still:

> No focused container found

It could be something like:

> Debug: No focused container found or autotiling turned off

What do you think?

**Comment by riscie** [comment]
Good additions, thank you! I've added them.

**Comment by nwg-piotr** [comment]
Excellent. Will merge when I'm back home.

**Pull request merged**
