### PR TITLE
Add `--debug` option

### PR DESCRIPTION
**Pull request by ammgws**
Adds a `--debug` mode that prints useful information for troubleshooting issues.

In the process a couple of other improvements were made.﻿

### CODE REVIEW

**Comment by ammgws** [comment]
Oops messed up the ordering in the main function when splitting commits. I'll fix it in a sec.

**Comment by nwg-piotr** [comment]
Well, I'm not sure if it's worth of adding 2 new imports. Could you justify?

**Comment by ammgws** [comment]
I was having some issues and needed to know whether the script was actually working or not.
(The catch-all try block only logs errors due to exceptions)

The imports themselves are from the standard library and from some testing the script startup time (which realistically only happens once per login) is increased to 26ms from 13ms which is negligible either way.

Anyway if it's getting a bit too complicated than intended then feel free to close.

**Comment by nwg-piotr** [comment]
LOL, at first I intended it to be as close to a one-liner as possible, but contributors decided otherwise. :) Actually I was just curious why you found it useful.

I'll merge it locally and see how it behaves on sway and i3, before merging your PR.

**Comment by ammgws** [comment]
I guess if someone happens to open an issue in the future, you could tell them to check the --debug log.

To be honest that catch-all try block is also so tempting to try and Python-ify as well lol.

**Comment by nwg-piotr** [comment]
This script is one of the shortest I've ever publish and the most modified by contributors. I wish the feature like this was just added to sway. :)

Let me get back to this later tonight, as I'm trying to refactor my C++ code in another project at the moment. Don't tell anyone: I'm useless at C++. :)

**Comment by nwg-piotr** [comment]
Thanks for contribution!

**Pull request merged**
